//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LookScoreAdmin.LookScoreWCF {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="LookScoreWCF.IGameService")]
    public interface IGameService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IGameService/GetAllGamesTitle", ReplyAction="http://tempuri.org/IGameService/GetAllGamesTitleResponse")]
        string[] GetAllGamesTitle();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IGameService/GetAllGamesTitle", ReplyAction="http://tempuri.org/IGameService/GetAllGamesTitleResponse")]
        System.Threading.Tasks.Task<string[]> GetAllGamesTitleAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IGameService/FindAllGames", ReplyAction="http://tempuri.org/IGameService/FindAllGamesResponse")]
        LookScoreInterfaces.Model.Entity.Game[] FindAllGames();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IGameService/FindAllGames", ReplyAction="http://tempuri.org/IGameService/FindAllGamesResponse")]
        System.Threading.Tasks.Task<LookScoreInterfaces.Model.Entity.Game[]> FindAllGamesAsync();
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IGameServiceChannel : LookScoreAdmin.LookScoreWCF.IGameService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class GameServiceClient : System.ServiceModel.ClientBase<LookScoreAdmin.LookScoreWCF.IGameService>, LookScoreAdmin.LookScoreWCF.IGameService {
        
        public GameServiceClient() {
        }
        
        public GameServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public GameServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public GameServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public GameServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public string[] GetAllGamesTitle() {
            return base.Channel.GetAllGamesTitle();
        }
        
        public System.Threading.Tasks.Task<string[]> GetAllGamesTitleAsync() {
            return base.Channel.GetAllGamesTitleAsync();
        }
        
        public LookScoreInterfaces.Model.Entity.Game[] FindAllGames() {
            return base.Channel.FindAllGames();
        }
        
        public System.Threading.Tasks.Task<LookScoreInterfaces.Model.Entity.Game[]> FindAllGamesAsync() {
            return base.Channel.FindAllGamesAsync();
        }
    }
}
