//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LookScoreViewerClient.LookScoreWCF {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Game", Namespace="http://schemas.datacontract.org/2004/07/LookScoreInterfaces.Model.Entity")]
    [System.SerializableAttribute()]
    public partial class Game : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime GameStartDateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string GameTitleField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private LookScoreViewerClient.LookScoreWCF.Club GuestClubField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private LookScoreViewerClient.LookScoreWCF.Club HomeClubField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IdField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime GameStartDate {
            get {
                return this.GameStartDateField;
            }
            set {
                if ((this.GameStartDateField.Equals(value) != true)) {
                    this.GameStartDateField = value;
                    this.RaisePropertyChanged("GameStartDate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string GameTitle {
            get {
                return this.GameTitleField;
            }
            set {
                if ((object.ReferenceEquals(this.GameTitleField, value) != true)) {
                    this.GameTitleField = value;
                    this.RaisePropertyChanged("GameTitle");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public LookScoreViewerClient.LookScoreWCF.Club GuestClub {
            get {
                return this.GuestClubField;
            }
            set {
                if ((object.ReferenceEquals(this.GuestClubField, value) != true)) {
                    this.GuestClubField = value;
                    this.RaisePropertyChanged("GuestClub");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public LookScoreViewerClient.LookScoreWCF.Club HomeClub {
            get {
                return this.HomeClubField;
            }
            set {
                if ((object.ReferenceEquals(this.HomeClubField, value) != true)) {
                    this.HomeClubField = value;
                    this.RaisePropertyChanged("HomeClub");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Id {
            get {
                return this.IdField;
            }
            set {
                if ((this.IdField.Equals(value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Club", Namespace="http://schemas.datacontract.org/2004/07/LookScoreInterfaces.Model.Entity")]
    [System.SerializableAttribute()]
    public partial class Club : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private string Countryk__BackingFieldField;
        
        private System.DateTime FormedYeark__BackingFieldField;
        
        private int Idk__BackingFieldField;
        
        private string LogoUrlk__BackingFieldField;
        
        private string Namek__BackingFieldField;
        
        private int PlayersCountk__BackingFieldField;
        
        private string ShortNamek__BackingFieldField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Name="<Country>k__BackingField", IsRequired=true)]
        public string Countryk__BackingField {
            get {
                return this.Countryk__BackingFieldField;
            }
            set {
                if ((object.ReferenceEquals(this.Countryk__BackingFieldField, value) != true)) {
                    this.Countryk__BackingFieldField = value;
                    this.RaisePropertyChanged("Countryk__BackingField");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Name="<FormedYear>k__BackingField", IsRequired=true)]
        public System.DateTime FormedYeark__BackingField {
            get {
                return this.FormedYeark__BackingFieldField;
            }
            set {
                if ((this.FormedYeark__BackingFieldField.Equals(value) != true)) {
                    this.FormedYeark__BackingFieldField = value;
                    this.RaisePropertyChanged("FormedYeark__BackingField");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Name="<Id>k__BackingField", IsRequired=true)]
        public int Idk__BackingField {
            get {
                return this.Idk__BackingFieldField;
            }
            set {
                if ((this.Idk__BackingFieldField.Equals(value) != true)) {
                    this.Idk__BackingFieldField = value;
                    this.RaisePropertyChanged("Idk__BackingField");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Name="<LogoUrl>k__BackingField", IsRequired=true)]
        public string LogoUrlk__BackingField {
            get {
                return this.LogoUrlk__BackingFieldField;
            }
            set {
                if ((object.ReferenceEquals(this.LogoUrlk__BackingFieldField, value) != true)) {
                    this.LogoUrlk__BackingFieldField = value;
                    this.RaisePropertyChanged("LogoUrlk__BackingField");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Name="<Name>k__BackingField", IsRequired=true)]
        public string Namek__BackingField {
            get {
                return this.Namek__BackingFieldField;
            }
            set {
                if ((object.ReferenceEquals(this.Namek__BackingFieldField, value) != true)) {
                    this.Namek__BackingFieldField = value;
                    this.RaisePropertyChanged("Namek__BackingField");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Name="<PlayersCount>k__BackingField", IsRequired=true)]
        public int PlayersCountk__BackingField {
            get {
                return this.PlayersCountk__BackingFieldField;
            }
            set {
                if ((this.PlayersCountk__BackingFieldField.Equals(value) != true)) {
                    this.PlayersCountk__BackingFieldField = value;
                    this.RaisePropertyChanged("PlayersCountk__BackingField");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Name="<ShortName>k__BackingField", IsRequired=true)]
        public string ShortNamek__BackingField {
            get {
                return this.ShortNamek__BackingFieldField;
            }
            set {
                if ((object.ReferenceEquals(this.ShortNamek__BackingFieldField, value) != true)) {
                    this.ShortNamek__BackingFieldField = value;
                    this.RaisePropertyChanged("ShortNamek__BackingField");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="LookScoreWCF.IGameService")]
    public interface IGameService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IGameService/GetAllGamesTitle", ReplyAction="http://tempuri.org/IGameService/GetAllGamesTitleResponse")]
        string[] GetAllGamesTitle();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IGameService/GetAllGamesTitle", ReplyAction="http://tempuri.org/IGameService/GetAllGamesTitleResponse")]
        System.Threading.Tasks.Task<string[]> GetAllGamesTitleAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IGameService/FindAllGames", ReplyAction="http://tempuri.org/IGameService/FindAllGamesResponse")]
        LookScoreViewerClient.LookScoreWCF.Game[] FindAllGames();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IGameService/FindAllGames", ReplyAction="http://tempuri.org/IGameService/FindAllGamesResponse")]
        System.Threading.Tasks.Task<LookScoreViewerClient.LookScoreWCF.Game[]> FindAllGamesAsync();
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IGameServiceChannel : LookScoreViewerClient.LookScoreWCF.IGameService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class GameServiceClient : System.ServiceModel.ClientBase<LookScoreViewerClient.LookScoreWCF.IGameService>, LookScoreViewerClient.LookScoreWCF.IGameService {
        
        public GameServiceClient() {
        }
        
        public GameServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public GameServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public GameServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public GameServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public string[] GetAllGamesTitle() {
            return base.Channel.GetAllGamesTitle();
        }
        
        public System.Threading.Tasks.Task<string[]> GetAllGamesTitleAsync() {
            return base.Channel.GetAllGamesTitleAsync();
        }
        
        public LookScoreViewerClient.LookScoreWCF.Game[] FindAllGames() {
            return base.Channel.FindAllGames();
        }
        
        public System.Threading.Tasks.Task<LookScoreViewerClient.LookScoreWCF.Game[]> FindAllGamesAsync() {
            return base.Channel.FindAllGamesAsync();
        }
    }
}
